export const data = [
  {
    name: "John Deo",
    id: "JK2346",
    storyId: "ST1234",
    gender: "Female",
    dob: "04/12/1990",
    country: "USA",
    mobileNumber: "+919087654321",
    email: "johndeo12@gmail.com",
    status: "Blacklisted",
    posts: "65",
    traffic: "22k",
    likes: "10M",
    followers: "4M",
    engagementRate: "8%",
    collaboration: "2+",
    uploadTime: "07-04-2025",
    trafficRatio: "20%",
    boostPrise: "$50",
    boostTime: "1 week",
    likeRatio: "25%",
    userTraffic: "35k",
    totalLikes: "10k",
    totalComments: "5k",
    Reply: "100",
    savedPost: "100",
    dailyActiveHours: 3,
    nonFollowersPer: "30%",
    followersPer: "70%",
    slug: "testingpurposeCategory",
  },
  {
    name: "John Deo",
    id: "AI9090",
    storyId: "ST5678",
    gender: "Male",
    dob: "04/12/1990",
    country: "India",
    mobileNumber: "+919876543210",
    email: "johndeo12@gmail.com",
    status: "Blacklisted",
    posts: "120",
    traffic: "30.5k",
    likes: "10M",
    followers: "1.2M",
    engagementRate: "5%",
    collaboration: "2+",
    uploadTime: "07-04-2025",
    trafficRatio: "30%",
    boostPrise: "$100",
    boostTime: "2 weeks",
    likeRatio: "30%",
    userTraffic: "30.5k",
    totalLikes: "10M",
    totalComments: "10M",
    Reply: "6M",
    savedPost: "N/A",
    dailyActiveHours: 6,
    nonFollowersPer: "50%",
    followersPer: "50%",
    slug: "testingpurposeCategory",
  },
  {
    name: "John Deo",
    id: "DE7532",
    storyId: "ST9101",
    gender: "Female",
    dob: "04/12/1990",
    country: "China",
    mobileNumber: "+916543210987",
    email: "johndeo12@gmail.com",
    status: "Inactive",
    posts: "30",
    traffic: "22.1k",
    likes: "10M",
    followers: "3.2M",
    engagementRate: "25%",
    collaboration: "3+",
    uploadTime: "07-04-2025",
    trafficRatio: "15%",
    boostPrise: "$30",
    boostTime: "5 days",
    likeRatio: "12%",
    userTraffic: "22.1k",
    totalLikes: "3k",
    totalComments: "1.5k",
    Reply: "800",
    savedPost: "200",
    dailyActiveHours: 1,
    nonFollowersPer: "45%",
    followersPer: "55%",
    slug: "testingpurposeCategory",
  },
  {
    name: "John Deo",
    id: "GH8923",
    storyId: "ST1121",
    gender: "Male",
    dob: "04/12/1990",
    country: "Japan",
    mobileNumber: "+913210987654",
    email: "johndeo12@gmail.com",
    status: "Blacklisted",
    posts: "100",
    traffic: "27.8k",
    likes: "10M",
    followers: "1.8M",
    engagementRate: "55%",
    collaboration: "3+",
    uploadTime: "07-04-2025",
    trafficRatio: "35%",
    likeRatio: "40%",
    boostPrise: "$80",
    boostTime: "3 weeks",
    userTraffic: "27.8k",
    totalLikes: "9M",
    totalComments: "10M",
    Reply: "6M",
    savedPost: "5k",
    dailyActiveHours: 1.5,
    nonFollowersPer: "60%",
    followersPer: "40%",
    slug: "testingpurposeCategory",
  },
  {
    name: "Jane Doe",
    id: "BI8452",
    storyId: "ST3141",
    gender: "Female",
    dob: "04/12/1990",
    country: "USA",
    mobileNumber: "+919643210876",
    email: "janedoe12@gmail.com",
    status: "Active",
    posts: "60",
    traffic: "25k",
    likes: "10M",
    followers: "1.2M",
    engagementRate: "5%",
    collaboration: "3+",
    uploadTime: "06-04-2025",
    trafficRatio: "22%",
    boostPrise: "$40",
    boostTime: "1 day",
    likeRatio: "18%",
    userTraffic: "25k",
    totalLikes: "4k",
    totalComments: "2k",
    Reply: "900",
    savedPost: "300",
    dailyActiveHours: 2,
    nonFollowersPer: "75%",
    followersPer: "25%",
    slug: "testingpurposeCategory",
  },
  {
    name: "John Deo",
    id: "CD6345",
    storyId: "ST5161",
    gender: "Male",
    dob: "1985-11-11",
    country: "Canada",
    mobileNumber: "+917654321098",
    email: "johndeo12@gmail.com",
    status: "Blacklisted",
    posts: "85",
    traffic: "24k",
    likes: "10M",
    followers: "5.2M",
    engagementRate: "35%",
    collaboration: "2+",
    uploadTime: "06-04-2025",
    trafficRatio: "28%",
    boostPrise: "$70",
    boostTime: "2 weeks",
    likeRatio: "35%",
    userTraffic: "24k",
    totalLikes: "8k",
    totalComments: "5k",
    Reply: "1k",
    savedPost: "400",
    dailyActiveHours: 4,
    nonFollowersPer: "80%",
    followersPer: "20%",
    slug: "testingpurposeCategory",
  },
  {
    name: "John Deo",
    id: "FG5623",
    storyId: "ST7181",
    gender: "Female",
    dob: "04/12/1990",
    country: "UK",
    mobileNumber: "+919087761234",
    email: "johndeo12@gmail.com",
    status: "Active",
    posts: "70",
    traffic: "30k",
    likes: "10M",
    followers: "1.5M",
    engagementRate: "25%",
    collaboration: "3+",
    uploadTime: "05-04-2025",
    trafficRatio: "35%",
    boostPrise: "$60",
    boostTime: "3 days",
    likeRatio: "42%",
    userTraffic: "30k",
    totalLikes: "6k",
    totalComments: "3k",
    Reply: "1.2k",
    savedPost: "500",
    dailyActiveHours: 8,
    nonFollowersPer: "25%",
    followersPer: "75%",
    slug: "testingpurposeCategory",
  },
  {
    name: "John Deo",
    id: "ZX9876",
    storyId: "ST9202",
    gender: "Male",
    dob: "04/12/1990",
    country: "Australia",
    mobileNumber: "+917654321675",
    email: "johndeo12@gmail.com",
    status: "Blacklisted",
    posts: "90",
    traffic: "28k",
    likes: "10M",
    followers: "3.2M",
    engagementRate: "15%",
    collaboration: "4+",
    uploadTime: "08-04-2025",
    trafficRatio: "38%",
    boostPrise: "$90",
    boostTime: "1 month",
    likeRatio: "40%",
    userTraffic: "28k",
    totalLikes: "7M",
    totalComments: "8M",
    Reply: "4M",
    savedPost: "3k",
    dailyActiveHours: 3,
    nonFollowersPer: "10%",
    followersPer: "90%",
    slug: "testingpurposeCategory",
  },
  {
    name: "John Deo",
    id: "LM4453",
    storyId: "ST1222",
    gender: "Female",
    dob: "04/12/1990",
    country: "India",
    mobileNumber: "+919654321321",
    email: "johndeo12@gmail.com",
    status: "Active",
    posts: "50",
    traffic: "20k",
    likes: "10M",
    followers: "1.5M",
    engagementRate: "10%",
    collaboration: "3+",
    uploadTime: "05-04-2025",
    trafficRatio: "18%",
    boostPrise: "$20",
    boostTime: "1 week",
    likeRatio: "22%",
    userTraffic: "20k",
    totalLikes: "5k",
    totalComments: "2k",
    Reply: "700",
    savedPost: "200",
    dailyActiveHours: 4,
    nonFollowersPer: "20%",
    followersPer: "80%",
    slug: "testingpurposeCategory",
  },

  {
    name: "John Deo",
    id: "OP4567",
    storyId: "ST3242",
    gender: "Male",
    dob: "04/12/1990",
    country: "USA",
    mobileNumber: "+919076543210",
    email: "johndeo12@gmail.com",
    status: "Blacklisted",
    posts: "95",
    traffic: "32k",
    likes: "10M",
    followers: "1.2M",
    engagementRate: "5%",
    collaboration: "4+",
    uploadTime: "07-04-2025",
    trafficRatio: "40%",
    boostPrise: "$120",
    boostTime: "2 months",
    likeRatio: "45%",
    userTraffic: "32k",
    totalLikes: "8M",
    totalComments: "9M",
    Reply: "5M",
    savedPost: "4k",
    dailyActiveHours: 5,
    nonFollowersPer: "50%",
    followersPer: "50%",
    slug: "testingpurposeCategory",
  },
  {
    name: "John Deo",
    id: "OP4567",
    storyId: "ST3242",
    gender: "Male",
    dob: "04/12/1990",
    country: "USA",
    mobileNumber: "+919076543210",
    email: "johndeo12@gmail.com",
    status: "Blacklisted",
    posts: "95",
    traffic: "32k",
    likes: "10M",
    followers: "1.2M",
    engagementRate: "5%",
    collaboration: "4+",
    uploadTime: "07-04-2025",
    trafficRatio: "40%",
    boostPrise: "$120",
    boostTime: "2 months",
    likeRatio: "45%",
    userTraffic: "32k",
    totalLikes: "8M",
    totalComments: "9M",
    Reply: "5M",
    savedPost: "4k",
    dailyActiveHours: 5,
    nonFollowersPer: "50%",
    followersPer: "50%",
    slug: "testingpurposeCategory",
  },
  {
    name: "John Deo",
    id: "OP4567",
    storyId: "ST3242",
    gender: "Male",
    dob: "04/12/1990",
    country: "USA",
    mobileNumber: "+919076543210",
    email: "johndeo12@gmail.com",
    status: "Blacklisted",
    posts: "95",
    traffic: "32k",
    likes: "10M",
    followers: "1.2M",
    engagementRate: "5%",
    collaboration: "4+",
    uploadTime: "07-04-2025",
    trafficRatio: "40%",
    boostPrise: "$120",
    boostTime: "2 months",
    likeRatio: "45%",
    userTraffic: "32k",
    totalLikes: "8M",
    totalComments: "9M",
    Reply: "5M",
    savedPost: "4k",
    dailyActiveHours: 5,
    nonFollowersPer: "50%",
    followersPer: "50%",
    slug: "testingpurposeCategory",
  },
  {
    name: "John Deo",
    id: "OP4567",
    storyId: "ST3242",
    gender: "Male",
    dob: "04/12/1990",
    country: "USA",
    mobileNumber: "+919076543210",
    email: "johndeo12@gmail.com",
    status: "Blacklisted",
    posts: "95",
    traffic: "32k",
    likes: "10M",
    followers: "1.2M",
    engagementRate: "5%",
    collaboration: "4+",
    uploadTime: "07-04-2025",
    trafficRatio: "40%",
    boostPrise: "$120",
    boostTime: "2 months",
    likeRatio: "45%",
    userTraffic: "32k",
    totalLikes: "8M",
    totalComments: "9M",
    Reply: "5M",
    savedPost: "4k",
    dailyActiveHours: 5,
    nonFollowersPer: "50%",
    followersPer: "50%",
    slug: "testingpurposeCategory",
  },
  {
    name: "John Deo",
    id: "OP4567",
    storyId: "ST3242",
    gender: "Male",
    dob: "04/12/1990",
    country: "USA",
    mobileNumber: "+919076543210",
    email: "johndeo12@gmail.com",
    status: "Blacklisted",
    posts: "95",
    traffic: "32k",
    likes: "10M",
    followers: "1.2M",
    engagementRate: "5%",
    collaboration: "4+",
    uploadTime: "07-04-2025",
    trafficRatio: "40%",
    boostPrise: "$120",
    boostTime: "2 months",
    likeRatio: "45%",
    userTraffic: "32k",
    totalLikes: "8M",
    totalComments: "9M",
    Reply: "5M",
    savedPost: "4k",
    dailyActiveHours: 5,
    nonFollowersPer: "50%",
    followersPer: "50%",
    slug: "testingpurposeCategory",
  },
  {
    name: "John Deo",
    id: "OP4567",
    storyId: "ST3242",
    gender: "Male",
    dob: "04/12/1990",
    country: "USA",
    mobileNumber: "+919076543210",
    email: "johndeo12@gmail.com",
    status: "Blacklisted",
    posts: "95",
    traffic: "32k",
    likes: "10M",
    followers: "1.2M",
    engagementRate: "5%",
    collaboration: "4+",
    uploadTime: "07-04-2025",
    trafficRatio: "40%",
    boostPrise: "$120",
    boostTime: "2 months",
    likeRatio: "45%",
    userTraffic: "32k",
    totalLikes: "8M",
    totalComments: "9M",
    Reply: "5M",
    savedPost: "4k",
    dailyActiveHours: 5,
    nonFollowersPer: "50%",
    followersPer: "50%",
    slug: "testingpurposeCategory",
  },
  {
    name: "John Deo",
    id: "OP4567",
    storyId: "ST3242",
    gender: "Male",
    dob: "04/12/1990",
    country: "USA",
    mobileNumber: "+919076543210",
    email: "johndeo12@gmail.com",
    status: "Blacklisted",
    posts: "95",
    traffic: "32k",
    likes: "10M",
    followers: "1.2M",
    engagementRate: "5%",
    collaboration: "4+",
    uploadTime: "07-04-2025",
    trafficRatio: "40%",
    boostPrise: "$120",
    boostTime: "2 months",
    likeRatio: "45%",
    userTraffic: "32k",
    totalLikes: "8M",
    totalComments: "9M",
    Reply: "5M",
    savedPost: "4k",
    dailyActiveHours: 5,
    nonFollowersPer: "50%",
    followersPer: "50%",
    slug: "testingpurposeCategory",
  },
  {
    name: "John Deo",
    id: "OP4567",
    storyId: "ST3242",
    gender: "Male",
    dob: "04/12/1990",
    country: "USA",
    mobileNumber: "+919076543210",
    email: "johndeo12@gmail.com",
    status: "Blacklisted",
    posts: "95",
    traffic: "32k",
    likes: "10M",
    followers: "1.2M",
    engagementRate: "5%",
    collaboration: "4+",
    uploadTime: "07-04-2025",
    trafficRatio: "40%",
    boostPrise: "$120",
    boostTime: "2 months",
    likeRatio: "45%",
    userTraffic: "32k",
    totalLikes: "8M",
    totalComments: "9M",
    Reply: "5M",
    savedPost: "4k",
    dailyActiveHours: 5,
    nonFollowersPer: "50%",
    followersPer: "50%",
    slug: "testingpurposeCategory",
  },
  {
    name: "John Deo",
    id: "OP4567",
    storyId: "ST3242",
    gender: "Male",
    dob: "04/12/1990",
    country: "USA",
    mobileNumber: "+919076543210",
    email: "johndeo12@gmail.com",
    status: "Blacklisted",
    posts: "95",
    traffic: "32k",
    likes: "10M",
    followers: "1.2M",
    engagementRate: "5%",
    collaboration: "4+",
    uploadTime: "07-04-2025",
    trafficRatio: "40%",
    boostPrise: "$120",
    boostTime: "2 months",
    likeRatio: "45%",
    userTraffic: "32k",
    totalLikes: "8M",
    totalComments: "9M",
    Reply: "5M",
    savedPost: "4k",
    dailyActiveHours: 5,
    nonFollowersPer: "50%",
    followersPer: "50%",
    slug: "testingpurposeCategory",
  },
  {
    name: "John Deo",
    id: "OP4567",
    storyId: "ST3242",
    gender: "Male",
    dob: "04/12/1990",
    country: "USA",
    mobileNumber: "+919076543210",
    email: "johndeo12@gmail.com",
    status: "Blacklisted",
    posts: "95",
    traffic: "32k",
    likes: "10M",
    followers: "1.2M",
    engagementRate: "5%",
    collaboration: "4+",
    uploadTime: "07-04-2025",
    trafficRatio: "40%",
    boostPrise: "$120",
    boostTime: "2 months",
    likeRatio: "45%",
    userTraffic: "32k",
    totalLikes: "8M",
    totalComments: "9M",
    Reply: "5M",
    savedPost: "4k",
    dailyActiveHours: 5,
    nonFollowersPer: "50%",
    followersPer: "50%",
    slug: "testingpurposeCategory",
  },
  {
    name: "John Deo",
    id: "OP4567",
    storyId: "ST3242",
    gender: "Male",
    dob: "04/12/1990",
    country: "USA",
    mobileNumber: "+919076543210",
    email: "johndeo12@gmail.com",
    status: "Blacklisted",
    posts: "95",
    traffic: "32k",
    likes: "10M",
    followers: "1.2M",
    engagementRate: "5%",
    collaboration: "4+",
    uploadTime: "07-04-2025",
    trafficRatio: "40%",
    boostPrise: "$120",
    boostTime: "2 months",
    likeRatio: "45%",
    userTraffic: "32k",
    totalLikes: "8M",
    totalComments: "9M",
    Reply: "5M",
    savedPost: "4k",
    dailyActiveHours: 5,
    nonFollowersPer: "50%",
    followersPer: "50%",
    slug: "testingpurposeCategory",
  },
  {
    name: "John Deo",
    id: "OP4567",
    storyId: "ST3242",
    gender: "Male",
    dob: "04/12/1990",
    country: "USA",
    mobileNumber: "+919076543210",
    email: "johndeo12@gmail.com",
    status: "Blacklisted",
    posts: "95",
    traffic: "32k",
    likes: "10M",
    followers: "1.2M",
    engagementRate: "5%",
    collaboration: "4+",
    uploadTime: "07-04-2025",
    trafficRatio: "40%",
    boostPrise: "$120",
    boostTime: "2 months",
    likeRatio: "45%",
    userTraffic: "32k",
    totalLikes: "8M",
    totalComments: "9M",
    Reply: "5M",
    savedPost: "4k",
    dailyActiveHours: 5,
    nonFollowersPer: "50%",
    followersPer: "50%",
    slug: "testingpurposeCategory",
  },
  {
    name: "John Deo",
    id: "OP4567",
    storyId: "ST3242",
    gender: "Male",
    dob: "04/12/1990",
    country: "USA",
    mobileNumber: "+919076543210",
    email: "johndeo12@gmail.com",
    status: "Blacklisted",
    posts: "95",
    traffic: "32k",
    likes: "10M",
    followers: "1.2M",
    engagementRate: "5%",
    collaboration: "4+",
    uploadTime: "07-04-2025",
    trafficRatio: "40%",
    boostPrise: "$120",
    boostTime: "2 months",
    likeRatio: "45%",
    userTraffic: "32k",
    totalLikes: "8M",
    totalComments: "9M",
    Reply: "5M",
    savedPost: "4k",
    dailyActiveHours: 5,
    nonFollowersPer: "50%",
    followersPer: "50%",
    slug: "testingpurposeCategory",
  },
];
